const data = [
  {
    id: "1",
    suite: "mac1-job3",
    pass: "23",
    fail: "6",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "2",
    suite: "Failed suite [MainTestsuite]",
    pass: "0",
    fail: "3",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "3",
    suite: "WindowsMachine4",
    pass: "74",
    fail: "27",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "4",
    suite: "Failed suite [home-page-tests]",
    pass: "0",
    fail: "6",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "5",
    suite: "Failed suite [mac2-job3]",
    pass: "0",
    fail: "6",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "6",
    suite: "MainTestsuite",
    pass: "132",
    fail: "41",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "7",
    suite: "WindowsMachine1",
    pass: "35",
    fail: "17",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "8",
    suite: "WindowsMachine3",
    pass: "44",
    fail: "5",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "9",
    suite: "mac3-job3",
    pass: "28",
    fail: "10",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "10",
    suite: "Failed suite [WindowsMachine4]",
    pass: "1",
    fail: "22",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "11",
    suite: "mac1-valid-fail-job2",
    pass: "0",
    fail: "2",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "12",
    suite: "Failed suite [WindowsMachine2]",
    pass: "0",
    fail: "2",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "13",
    suite: "home-page-tests",
    pass: "19",
    fail: "12",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "14",
    suite: "win-2-valid-fail-test-cases",
    pass: "1",
    fail: "15",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "15",
    suite: "Failed suite [mac1-job3]",
    pass: "0",
    fail: "6",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "16",
    suite: "Failed suite [WindowsMachine1]",
    pass: "0",
    fail: "15",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "17",
    suite: "Failed suite [WindowsMachine3]",
    pass: "0",
    fail: "5",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "18",
    suite: "mac4-job3",
    pass: "30",
    fail: "7",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "19",
    suite: "Failed suite [mac3-job3]",
    pass: "1",
    fail: "9",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "20",
    suite: "mac2-job3",
    pass: "11",
    fail: "6",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "21",
    suite: "widget-test",
    pass: "0",
    fail: "4",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "22",
    suite: "Failed suite [mac4-job3]",
    pass: "0",
    fail: "7",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "23",
    suite: "mac5-valid-fail-job1",
    pass: "6",
    fail: "10",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "24",
    suite: "win-5-valid-fail-test-cases",
    pass: "5",
    fail: "13",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
  {
    id: "25",
    suite: "performance-benchmark-suite",
    pass: "190",
    fail: "874",
    skip: "0",
    defect: "0",
    maintainance: "0",
  },
];
const keyName = "status";
function getStringCountInArrayOfObjects(arrayOfObjects, keyName, value) {
  let countOfValue = 0;
  arrayOfObjects.filter((element) => {
    if (element.status === value) {
      countOfValue++;
    }
  });
  return countOfValue;
}

const getSumByKey = (data, key) => {
  return data.reduce(
    (accumulator, current) => accumulator + Number(current[key]),
    0
  );
};

const total = getSumByKey(data, "pass");
console.log(total);
